language: node_js
node_js: "8.11.1"

cache:
  directories:
    - "node_modules"

install:
  - npm install

before_script:
  - npm run build

script:
  - npm run test-all-cvr

after_success:
  - npm run coverage

before_deploy:
  - npm run build
  - npm run cix-lic

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    tag: "latest"
    on:
      branch: $NPM_ON_LATEST
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    tag: "next"
    on:
      branch: $NPM_ON_NEXT
